SHOW TABLES IN SCHEMA BWT_DATABASE.BWTSCHEMA;

SHOW SCHEMAS IN DATABASE BWT_DATABASE;

SHOW DATABASES;

---  HOW TO SET THE TIME CREATE AT TABLE

CREATE OR REPLACE TABLE BWT_DATABASE.BWTSCHEMA.time_travel
(
id number,
name string
);
---- retention time one day ---
show tables like 'time_travel';


---- IT CREATE A TIME TRAVEL FOR 10 DAYS -- SYTEX OF TIME TRAVELA -DATA_RETENTION_TIME_IN_DAYS =
CREATE OR REPLACE TABLE BWT_DATABASE.BWTSCHEMA.time_travel(id number,name string)
DATA_RETENTION_TIME_IN_DAYS = 10;
---- SHOW RETENTION PERIOD ----
show tables like 'time_travel';

---- ALTER RETENTION PERIOD AFTER CREATING TABLE ---
ALTER TABLE BWT_DATABASE.BWTSCHEMA.time_travel
SET DATA_RETENTION_TIME_IN_DAYS = 20;

-----------------------------------------------------------------------------
--- UPDATE FOR THE RECORD --
SELECT * FROM  BWT_DATABASE.BWTSCHEMA.EMPLOYEE_NEW;

UPDATE BWT_DATABASE.BWTSCHEMA.EMPLOYEE_NEW SET ENAME = 'ROHIT'
WHERE EID = 3001;

----- DELETE FOR THE RECORD ---
SELECT * FROM  BWT_DATABASE.BWTSCHEMA.EMPLOYEE_NEW;

DELETE FROM BWT_DATABASE.BWTSCHEMA.EMPLOYEE_NEW WHERE EID = 3004;

---- UPDATE SAME DATA ---

SELECT * FROM BWT_DATABASE.BWTSCHEMA.NEW_EMP;

UPDATE BWT_DATABASE.BWTSCHEMA.NEW_EMP SET ESAL = 30000 WHERE EID = 3001;

---------------------------------------------------------------------------------------

--- 1 .RETRIEVE HISTORY DATA BY USING AT OFFSET ---

SELECT * FROM  BWT_DATABASE.BWTSCHEMA.EMPLOYEE_NEW WHERE  EID = 3001;
   --- SHOW HISTORY DATA ---
SELECT * FROM  BWT_DATABASE.BWTSCHEMA.EMPLOYEE_NEW AT (OFFSET =>-60*20)
WHERE  EID = 3001;

--- 2. RETRIEVE HISTORY DATA BY USING TIMESTAMP --

SELECT *
FROM BWT_DATABASE.BWTSCHEMA.NEW_EMP
AT (TIMESTAMP => '2024-05-30 09:48:47.145'::TIMESTAMP)
WHERE EID = 3001;

--- 3. RETRIEVE HISTORY DATA BY USING BEFORE STATEMENT 
SELECT * FROM BWT_DATABASE.BWTSCHEMA.EMPLOYEE_NEW 
BEFORE (STATEMENT => '01b4b05c-0001-24b6-0004-643e0001445e')
WHERE EID = 3004;

  ---- CREATE TABLE FOR THIS DELETE RECORD FOR THIS TABLE ---
CREATE OR REPLACE TABLE BWT_DATABASE.BWTSCHEMA.EMP_NEW_DEL
AS
SELECT * FROM BWT_DATABASE.BWTSCHEMA.EMPLOYEE_NEW 
BEFORE (STATEMENT => '01b4b05c-0001-24b6-0004-643e0001445e')
WHERE EID = 3004;

SELECT * FROM BWT_DATABASE.BWTSCHEMA.EMP_NEW_DEL


-----------------------------------------------------------------------------------

---- RESTORING TABLES ----
DROP TABLE BWT_DATABASE.BWTSCHEMA.CUSTOMER_NEW;
   ---- WELL RESTORING THE TABLE ---
UNDROP TABLE BWT_DATABASE.BWTSCHEMA.CUSTOMER_NEW;